### ISSUE TITLE
Lack of improvent when training arff datasets

### ISSUE THREAD

**Issue by Migue8gl** [Valdecy/pyMetaheuristic#11]
I am using the goa.py algorithm for optimization tasks, specifically training on an ARFF dataset. However, I've noticed that the algorithm does not show improvement along iterations when using this dataset. 
This is the fitness landscape during the optimization process to provide visual evidence of the lack of improvement. Is ionosphere dataset, but the fitness curves are the same for other datasets.
![KNN_fitness_5_fold_cross_validation_goa_real_ionosphere](https://github.com/Valdecy/pyMetaheuristic/assets/63297070/23fb7818-fddc-4914-9537-654eeb74539d)

**Comment by Migue8gl** [comment]
Must say that I believe this behaviour is not because of my code, I did use other pyMetaheuristic algorithms and they show great improvements over time in the fitness value returned during training.

**Comment by Valdecy** [comment]
The Grasshopper Optimization Algorithm (GOA) can encounter difficulties in converging when dealing with high-dimensional problems. To address potential stagnation, I've implemented a mechanism to reinitialize the search space whenever the algorithm seems stuck. I encourage you to check out version 1.9.5 of pyMetaheuristic for this update. If your issue persists, please share your code with me. I will attempt to reproduce the error and work towards a resolution.
