### ISSUE TITLE
question about particle swarm optimization modification

### ISSUE THREAD

**Issue by natureoptics7** [Valdecy/pyMetaheuristic#12]
I wonder if it is possible to add more parameters just for particle swarm optimization.
Only two parameter optimizations are now available. (For example, 50 parameters, not 2)

**Comment by Valdecy** [comment]
The PSO implementation can solve for any number of variables. To do this, adjust your target function to accept a list of variables. Additionally, you need to set the minimum and maximum limits for each variable. For example, if you want to use three variables for a specific target function, you would set: 

min_values = [-5.12, -5.12, -5.12]
max_values = [ 5.12,  5.12,   5.12]
