### ISSUE TITLE
Questions to ask

### ISSUE THREAD

**Issue by tumu1234** [Valdecy/pyMetaheuristic#3]
Blogger hello，What causes this error when using your project？No module named 'pyMetaheuristic.algorithm'; 'pyMetaheuristic' is not a package

**Comment by Valdecy** [comment]
This link should help you: https://stackoverflow.com/questions/36250353/importing-installed-package-from-script-raises-attributeerror-module-has-no-at

**Comment by tumu1234** [comment]
![QQ图片20220323151457](https://user-images.githubusercontent.com/101096178/159644065-423a1342-f4d0-46a7-9939-9eaf079ac184.png)
Hello, I still have this problem
thanks

**Comment by Valdecy** [comment]
I noticed by the error that you are usin PyCharm, so try this link instead: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000407910-Can-Import-Modules-in-Pycharm-ModuleNotFoundError-Problem-Fixed
