### ISSUE TITLE
modified graphs.py

### ISSUE THREAD

**Issue by xichaoqiang** [Valdecy/pyMetaheuristic#5]
Hello I think scatter is not beautiful.
[graphs.zip](https://github.com/Valdecy/pyMetaheuristic/files/9572644/graphs.zip)
3D plot
![image](https://user-images.githubusercontent.com/30900789/190335791-a47f0a6e-1ac6-4076-9224-fbaed19ab3eb.png)
2D plot
![image](https://user-images.githubusercontent.com/30900789/190335962-a67fc2de-7da2-43be-8ab5-adcf87e2213e.png)

**Comment by Valdecy** [comment]
Ok. I'll check on that
