### ISSUE TITLE
Bounds not observed in some routines

### ISSUE THREAD

**Issue by zos474** [Valdecy/pyMetaheuristic#8]
Hello, this is such a wonderful package. I really appreciate your work on this. I have noticed that in some routines the bounds are not observed (i.e. one of the particles will be set outside of min/max values.) One such case is for the moth flame routine and it looks like an np.clip has been left out in the update_position routine:

position[i,j]  = flame_distance*math.exp(b_constant *rnd_2)*math.cos(rnd_2*2*math.pi) + flames[i,j]

should be

position[i,j]  = np.clip(flame_distance*math.exp(b_constant *rnd_2)*math.cos(rnd_2*2*math.pi) + flames[i,j], min_values[j],  max_values[j])

as per the alternate position case. Please would you be so kind as to fix this?

**Comment by Valdecy** [comment]
Thank you for using pyMetaheuristic! Regarding the issue you've encountered, may I inquire if you are using the latest version of pyMetaheuristic (version 1.4.1)? In the source code, specifically at line 56 in [mfa.py](https://github.com/Valdecy/pyMetaheuristic/blob/main/pyMetaheuristic/algorithm/mfa.py), you'll find that the `np.clip` function has already been implemented to handle boundary conditions.

**Comment by zos474** [comment]
Hi again, I was referring to line 51, which seems to be missing the clip. I haven't tried to dig into the code too much, so excuse me if I am misunderstanding something. I just know that when I run the code it has calls that are outside the variable bounds (I figured this out because I have a very expensive objective function, so am recording all the calls.)  This only seems to happen after the first or second generation. As an example, I have bounds of 0 to 0.7 on one variable and it is sending calls that have this variable negative at times.  I don't see this happening with almost all the other routines I have tried. I think there was one more, but I forget which one right now.

**Comment by Valdecy** [comment]
Just so you know, I'm in the process of finding another metaheuristic algorithm that also exhibits the np.clip issue. In the meantime, I recommend using version 1.4.2 of the pyMetaheuristic library, as the Moth Flame Algorithm has been updated.
