### ISSUE TITLE
Questions about Food/Predator update strategy in Dragonfly Algorithm

### ISSUE THREAD

**Issue by Xrondev** [Valdecy/pyMetaheuristic#9]
Great repo! I'm recently researching on the Dragonfly Algorithm, and try to implement it. For the README link to original paper, it seems that the original paper should be "_Dragonfly algorithm: a new meta-heuristic optimization technique for solving single-objective, discrete, and multi-objective problems_" published May 2015, https://link.springer.com/article/10.1007/s00521-015-1920-1 (if the "original paper" refers to the paper which proposed the algorithm, not the paper which help implemented the algorithm)

---
I have read through the "origin" one and the one mentioned in the README (roughly), it seems both paper didn't introduce how to update the food and predator in detail.
## Environment
I am working on the source code instead of using it as package since I am trying to figure out what is wrong. I am applying an SVM as my target function, and return (1-accuracy) as the DA seems to minimize the target function instead of maximize it. And the seach space is on hyperparameter C (1, 1000) and Sigma (the RBF kernel, (1,100)).  
## Problem:  
For C and Sigma, the value should obviously be positive, however, the algorithm will update the Food to 0 and send it to the target function in some case (demensions != dragonflies.shape[1]-1, no neighbors?), I am confused on why should we place food to 0 (and 1-d zero), is that trying to remove the food attraction impact on the velocity update? Sending a 0 to target function may violates the min and max restriction isn't it?
  
If I just misunderstood any line or the usage of the function please let me know, appreciate if you can explain or figure out my mistake, thanks!

**Comment by Valdecy** [comment]
Thank you for your keen observations and valuable feedback on the Dragonfly Algorithm implementation. Indeed, the reference you mentioned is the foundational paper for this algorithm, but the paper cited in the README guided this code implementation.

Your observation about the update mechanism leading to potential zero values for C and Sigma is insightful. In the original implementation, setting the food position to zero in certain conditions (e.g., when dimensions do not match or there are no neighbors) was a simplistic approach to negate the food's influence. However, as you correctly pointed out, this can violate the minimum and maximum bounds of the parameters.

Based on your feedback, I have revised the code to ensure that new positions remain within the problem's bounds, addressing your highlighted issue ( food_position[0,k] = np.clip(food_position[0,k] + levy_flight(beta = 1.5)*food_position[0,k], min_values[k], max_values[k])  ). This adjustment should prevent the algorithm from suggesting non-feasible values like zero for the parameters and encourage a broader search.

While the Dragonfly Algorithm offers certain advantages, it may not always be the most efficient for every optimization problem, as you've observed in your research. Exploring other algorithms might yield better results for your specific case, and I encourage this exploration.

I appreciate your engagement with the repository and initiative in addressing these concerns. If you have any more insights or require further assistance, please feel free to contact me.
